### PR TITLE
beaglebone black: upgrade uboot version to 2019.04 and apply uboot-level overlay loading

### PR DESCRIPTION
**Pull request by doudou**
This PR upgrades the uboot version used for the BeagleBone Black to 2019.04, and implements the BBB-specific overlay loading.

Recent BBB images load DTBs and DTB overlays from uboot itself. The BBB maintainers have an off-tree uboot patch for this, but they depend on uboot 2019.04, and the uboot script(s) used to implement it were not compatible with mender out of the box.

This is my very first time touching uboot ... so I've probably done stuff I shouldn't have. The "unofficial" changes (that is, the changes I made myself) are basically in the last commit of the branch. The rest is u-boot code and/or BBB code.

The summary of the changes are:

- merge the official u-boot 2019.04 release
- forward-port the Mender config changes from `am335x_boneblack(_emmc)?_defconfig` to the official BBB configuration (`am335x_evm_defconfig` and `am335x_boneblack_defconfig`).
- port the `uname_boot` script from TI's boot code to the mender variables.

This is not heavily tested (basically checked it boots from the expected partition, and loads DTBs and overlays). It's really meant for review from people that would know more than I do (easy).

### CODE REVIEW

**Comment by mirzak** [comment]
This can not be merged in to `mender-bbb-2018.07` as we keep the different versions in different branches.

I can create a "base" mender-bbb-2019.04 branch for you and that is where you should target the PR

**Comment by doudou** [comment]
> This can not be merged in to `mender-bbb-2018.07` as we keep the different versions in different branches.
> 
> I can create a "base" mender-bbb-2019.04 branch for you and that is where you should target the PR

I was expecting something like that. Note that one can change the base branch of a PR which would avoid the hassle of creating a whole new PR. Could you reopen the PR and create the base branch you are referring to ?

**Comment by doudou** [comment]
Ping ?

**Comment by drewmoseley** [comment]
I have WIP branch here: https://github.com/drewmoseley/uboot-mender/tree/mender-bbb-2019.07

**Comment by doudou** [comment]
> I have WIP branch here: https://github.com/drewmoseley/uboot-mender/tree/mender-bbb-2019.07

I'm sorry, but I'd need a tad more communication than that.

Are you a mender developer ? If you are, why not use the code I've done ? What was wrong with it ? What will be the difference between what you've done and what I did ? Am I expected to create a new PR against your new code, or just forget what I did and hope that I'll be able to use what you are doing ?

As the PR description says, I've modified the bootscript behavior to match the one from debian (read kernel and DTBs from the uEnv.txt file). Is that something that you kept ?

**Comment by drewmoseley** [comment]
Hi @doudou yes I am a mender developer.  We can't use this PR because it's 4000+ commits. Mine is a clean start using the version 2019.07 plus patches from Yocto meta-mender.  If you can help identify the specific changes you made on top of stock UBoot we can take a look.  Or if you can just rebase this PR against my WIP branch that may be instructive.

**Comment by doudou** [comment]
> We can't use this PR because it's 4000+ commits.

It was the three top commits coming from me, and 4000+ commits coming from u-boot. Your branch should have the same 4000 commits if you pulled the u-boot changes.

The real changes are two commits (out of three) that come from the "official" BBB-Debian integration. One commit on top (the tip of this branch) coming from me. These three commits are the three at the top of the branch.

**Comment by drewmoseley** [comment]
I'll leave it to @mirzak to decide how to proceed here.  We generally try to stay with as close to pristine sources as possible and the overlay loading stuff is a fairly substantial patch. I think the uEnv stuff is probably OK but if you can break it into a separate commit for review that would be helpful.

That said, I believe there are efforts in the works, to be able to use the unmodified UBoot from Debian.  @mirzak can you comment on that?

**Comment by doudou** [comment]
To be honest, without the overlay loading, I have zero interest working on this. I really don't want to have a separate image between Debian and Mender, so I'll just stick to my version/branch.

**Comment by drewmoseley** [comment]
Understood.  Would it work properly using the unmodified UBoot from Debian?

**Comment by doudou** [comment]
> Would it work properly using the unmodified UBoot from Debian?

In principle, yes. But I don't quite understand how you plan to pull this off. One major feature I have right now is the ability to switch kernels and overlays between mender artifacts (since the uEnv.txt file is per-partition, it comes naturally). Being able to change kernels is something I've lost on the Grub integration (for plain Ubuntu images on x86), and am missing it.

**Pull request closed without merging**
